### ISSUE TITLE
Handle rss and json urls

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-url-management-api-read-client#28]
For streams in particular, and other types of page possibly, .rss and .json urls exist under the old url structure and should probably be mapped to vanity urls in a way that is somewhat intelligent i.e. automatically supported for each vanity, but also (maybe) possible to override by manually setting an .rss or .json url.

Sitting on this PR https://github.com/Financial-Times/n-url-management-api-read-client/pull/27 as it needs some thought as to how to manage this

**Comment by matthew-andrews** [comment]
I think we should do this by query params (&format=rss, etc)
